### PR TITLE
Adopt the new way of continuing queries

### PR DESCRIPTION
**Pull request by ricordisamoa**
Simpler and more consistent.

### CODE REVIEW

**Comment by cyberpower678** [comment]
I don't get it.

**Comment by ricordisamoa** [comment]
Sure, I should have added some context.
MediaWiki 1.21 greatly simplified the continuation system of the `action=query` API: instead of knowing exactly where the continuation keys are in the response, all you need is to merge the top-level `continue` object. For example, this could make it easier to handle continuation in a single place of the codebase.

**Comment by cyberpower678** [comment]
Sorry for the late response.  I am aware of the new way of querying but I chose this, because I'm familiar with it and I know it works.  Have you tested this code?

**Comment by ricordisamoa** [comment]
I admit I've not tested the code. Are there any automated tests I can run without actually editing?

**Comment by cyberpower678** [comment]
You can setup a local instance of the bot and point the run page to any page not containing “enable”.  That disables the bot from editing, while allowing full functionality otherwise.

**Comment by Niharika29** [comment]
@cyberpower678 since you already have a local instance setup, maybe it'll be easier for you to test this than for someone to setup the bot locally.

**Comment by ricordisamoa** [comment]
It should be tested by someone who is familiar with the bot's code, query continuation, and the resulting edits.

**Comment by cyberpower678** [comment]
I haven't forgotten about it,  I'm just holding off until I have some other bugs fixed.

**Comment by ricordisamoa** [comment]
@cyberpower678 I didn't mean to pressure you, what I meant is that I didn't feel confident enough to test it myself soon.

**Comment by cyberpower678** [comment]
No worries.  The changes itself looks good, but I'll merge it when I'm close to finishing the bot for the english wikipedia.

**Comment by cyberpower678** [comment]
Going to give this a go.

**Comment by ricordisamoa** [comment]
Oh thank you.

**Pull request merged**
